### ISSUE TITLE
[SUGGESTION] Use vanilla terrain generation for terrain generated beyond what is specified in the png

### ISSUE THREAD

**Issue by fredderf121** [28Pollux28/ImageWorldGenerator#10]
If I'm not mistaken, once we travel beyond the terrain that is to be generated by the png image, the terrain defaults to generating a single biome (as specified in the configs). It would be appreciated if this terrain could instead be generated using the default vanilla world generation, so that one could draw out their dream spawn area, but then have random world generation beyond a certain radius for exploration.

**Comment by 28Pollux28** [comment]
The problem would be that biomes wouldn't match at the border of the image, resulting in a weird separation between the image and the rest of the world.

**Comment by fredderf121** [comment]
Does that not already happen with the single biome default? Unless it is difficult to code in, there isn't any harm in adding the feature in, as I'm sure most would accept the border-separation compromise for a custom-spawn survival world.

**Comment by 28Pollux28** [comment]
Well gonna implement that when I have the time, thanks for the suggestion
