### ISSUE TITLE
.json works but generates mismatched biomes

### ISSUE THREAD

**Issue by NightHaunter111** [28Pollux28/ImageWorldGenerator#19]
Hello! My team is using your mod to generate a world from an image using biomes added by Oh the Biomes You'll Go (BYG). I've attached the imggen.json file we're using. We're running into some issues - 

1) ImageWorldGenerator generates outlines and biome shapes, but doesn't use vanilla biomes, and mismatches biomes compared to how we've defined their color coding in the .json.

2) ImageWorldGenerator often outright ignores the image we provide, despite setting the proper world-type and updating the name of the image we're using.
[imggen.txt](https://github.com/28Pollux28/ImageWorldGenerator/files/6469527/imggen.txt)

**Comment by 28Pollux28** [comment]
Could you please specify the BYG version, and if possible attach some of the logs, as it contain some informations.

**Comment by 28Pollux28** [comment]
For point are you on client or server. Because on client version, you have to do your edits and then choose the Image Generator world type in order to refresh the config/image

**Comment by NightHaunter111** [comment]
I'm currently testing this with my team with client, but I'm planning to eventually move this to server. We are using [Biomes You Go 1.1.7 MCV: 1.16.4/1.16.5
](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/3239861). I have attached the latest logs.
[latest.txt](https://github.com/28Pollux28/ImageWorldGenerator/files/6469557/latest.txt)

**Comment by 28Pollux28** [comment]
Ok the first issue is that in the imggen.json, you need to add 0x before the color codes. At the moment you have RRGGBB, where you need 0xRRGGBB. I also noticed that a lot of byg biomes are experiencing errors upon start up. Do they generate if you choose to create a normal overworld type world ?

**Comment by NightHaunter111** [comment]
Yes. We fixed the issue, but I'm not sure how. Thank you!!
