### ISSUE TITLE
[BUG] Void world problem & files

### ISSUE THREAD

**Issue by eiqq** [28Pollux28/ImageWorldGenerator#22]
**Describe the bug**
I commented about this problem, at curseforge page as 'EIQUI'

here is my config(default) and imggen folder
[New folder (2).zip](https://github.com/28Pollux28/ImageWorldGenerator/files/6987467/New.folder.2.zip)

and here is my mods I used
[mods.zip](https://github.com/28Pollux28/ImageWorldGenerator/files/6987473/mods.zip)

before I upload it, I tested finally, but it still generates void world and Minecraft has closed by crash

**To Reproduce**
mod just generates void world

**Expected behavior**

**Screenshots**
![2021-08-09_17 30 24](https://user-images.githubusercontent.com/79748558/129466068-8095e119-6dad-4bad-bba1-22b5ce56c61b.png)

**Version**
Mod Version :  1.3.3
Fabric Version : 0.11.6
Environment : Client or Server

**Comment by 28Pollux28** [comment]
Just saw your comment on Curseforge, glad it worked !
