### ISSUE TITLE
Datapack Support [SUGGESTION] 

### ISSUE THREAD

**Issue by WannaGrenade** [28Pollux28/ImageWorldGenerator#25]
Since you can locate a fabric mods location for biomes and generate it, with "modid:biomeid", is it possible to do the same so it also doesn't just search the fabric mod folder but the world/datapack folder so you also have an additional search option for "datapackid:biomeid". 

For example terralith a datapack that adds 100+ biomes and has it it that the biome id ingame f3 menu would be terralith:yosemitecliffs . So you have it locate that source.

**Comment by 28Pollux28** [comment]
Datapacks are already supported.

**Comment by WannaGrenade** [comment]
I'm confused then.

I downloaded [terralith](https://www.planetminecraft.com/data-pack/terralith-overworld-evolved-100-biomes-caves-and-more/) for more biomes, wondering if the fabric mod could support it. I installed terralith.zip in the world/datapack folder. 

I should note these do not MODIFY vanilla biomes but introduces NEW biomes by using 1.16 introduced biome jsons.

I then made a ['biomeImage.png'](https://imgur.com/zyN5UTX) map ONLY for vanilla biomes, desert, snow_tundra, and ice caps excluding any terralith biomes and installed it in imgen/image.

I used this config:
`{
  "configVersion": "1.3.3",
  "biomesImageName": "biomeImage.png",
  "biomesImageScale": 8.0,
  "repeatBiomeImage": false,
  "repeatMirrorBiomeImage": false,
  "defaultBiome": "minecraft:ocean",
  "continuousGen": true,
  "largeBiomes": false,
  "customBiomes": [
    {
      "biomeID": "modid:biomeid",
      "RGB": "0x000000"
    },
    {
      "biomeID": "modid:biomeid",
      "RGB": "0xFFFFFF"
    }
  ],
  "customHeightMap": false,
  "heightMapName": "HeightMap.png",
  "heightMapScale": 1.0,
  "repeatHeightMapImage": false,
  "repeatMirrorHeightMapImage": false,
  "seaLevel": 63,
  "placeVanillaStructures": true,
  "customStructures": false,
  "customStructuresImage": "structureMap.png",
  "repeatStructureImage": false,
  "repeatMirrorStructureImage": false,
  "useBlackList": false,
  "blackListApplication": 2,
  "structureBlacklist": [
    "modid:structureid",
    "modid:structureid"
  ],
  "customStructuresRGB": [
    {
      "structureID": "modid:structureid",
      "RGB": "0x123456"
    },
    {
      "structureID": "modid:structureid",
      "RGB": "0x024680"
    }
  ],
  "lakeFormationPercentChance": 0.5,
  "segmentImageWidth": 512,
  "segmentImageHeight": 512,
  "imageCacheSize": 4
}`

I encountered issues. I was able to narrow it down to this.

When my datapack is not installed and region files are regenerated the world appears like the map. [no datapack loaded](https://imgur.com/UXvbqgz)

When my datapack is installed I do not get imgen generation. [datapack loaded](https://imgur.com/kVy4wUS)

Do I have to create biome color codes for all new loaded biomes first? Or is there in an issue how datapack files are read? Or the datapack itself? Or am i handling this?

**Comment by 28Pollux28** [comment]
I'll check and see why this is happening.

**Comment by WannaGrenade** [comment]
Wanted to give some more info. It might be more than the just datapacks.

https://imgur.com/a/AxhTyIq

I decided to try using the terralith fabric mod version instead of the datapack and similarly as before, once generating new chunks, world generations returns soley to normal/terralith generation and does not follow the image. 

This is my map image: https://imgur.com/lAK8GH4

Do you think it might just be that biome pack or that all the new biomes must be labeled in the config first?

I can also provide the setup of my server if it helps you easier to retest this issue. I have been testing this mod on a small server with all the minimal resources needed for just this mod. 

EDIT: It appears to occur regardless if its a datapack or fabric mod, and this is occurring whenever these add ons introduce new biomes
