### ISSUE TITLE
Exception in server tick loop - Crashes on startup 

### ISSUE THREAD

**Issue by T3mp0st** [28Pollux28/ImageWorldGenerator#28]
Having some issues loading up the mod using a biome and heightmap. I have 16 GB ram so I somewhat doubt its running out of memory, I will post the crash report and config below

Crash report - [https://pastebin.com/4Dnx8DaP](url)

Config - [https://pastebin.com/qkvaq4c9](url)

**Comment by 28Pollux28** [comment]
You should try to open with a different software your heightmap png, and save it again
