### ISSUE TITLE
Link to "Adding Custom Biomes" in Wiki is broken

### ISSUE THREAD

**Issue by kientuong114** [28Pollux28/ImageWorldGenerator#3]
**Describe the bug**
The link in the [main wiki page](https://github.com/28Pollux28/ImageWorldGenerator/wiki) for adding custom biomes link to https://github.com/28Pollux28/ImageWorldGenerator/wiki/Adding-Custom-Biomes instead of linking to the actual page https://github.com/28Pollux28/ImageWorldGenerator/wiki/Adding-Custom-Biomes-or-Structures

**Expected behavior**
Link should go to the correct page

**Comment by 28Pollux28** [comment]
Fixed
